# Generated by Django 4.0.2 on 2022-02-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
