version: "3.9"
services:   
  smart-iam:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MODE: development
    environment:
      MODE: "development"
      SECRET_KEY: "a18f1560a28025d48d"
      DB_HOST: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
    container_name: smart-iam
    volumes:
      - ./:/code
    ports:
      - "8010:8010"
    stdin_open: true
    tty: true
