# Generated by Django 4.0.2 on 2022-02-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_staff_customuser_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="superuser",
            new_name="is_superuser",
        ),
    ]
