# Generated by Django 4.0.2 on 2022-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accountproducts",
            constraint=models.UniqueConstraint(
                fields=("account", "product"), name="unique_product_per_account"
            ),
        ),
    ]
