# Generated by Django 4.0.2 on 2022-03-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0002_alter_permissions_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionsCreateSerializer",
            fields=[
                (
                    "permissions_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="permissions.permissions",
                    ),
                ),
            ],
            bases=("permissions.permissions",),
        ),
    ]
