# Generated by Django 4.0.2 on 2022-03-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_permissionscreateserializer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermissionsCreateSerializer",
        ),
    ]
